Repository apache/skywalking-satellite, pull requests merged in 2020-12, with the labels that each got.

#5 Add API && Plugin framework registry
  README.md
  configs/config.yaml
  docs/project_structue.md
  go.mod
  go.sum
  internal/pkg/event/event.go
  internal/pkg/logger/log.go
  internal/pkg/logger/log_test.go
  internal/pkg/plugin/define.go
  internal/pkg/plugin/registry.go
  internal/satellite/event/event.go
  plugins/client/api/client.go
  plugins/client/example/client.go
  plugins/client/example/client_test.go
  plugins/client/grpc/README.md
  plugins/client/kakka/README.md
  plugins/collector/api/collector.go
  plugins/collector/example/collector.go
  plugins/collector/example/collector_test.go
  plugins/collector/log-grpc/README.md
  plugins/fallbacker/api/fallbacker.go
  plugins/fallbacker/example/fallbacker.go
  plugins/fallbacker/example/fallbacker_test.go
  plugins/filter/api/filter.go
  plugins/filter/example/filter.go
  plugins/filter/example/filter_test.go
  plugins/filter/sampling/README.md
  plugins/forwarder/api/forwarder.go
  plugins/forwarder/example/forwarder.go
  plugins/forwarder/example/forwarder_test.go
  plugins/forwarder/segment/README.md
  plugins/parser/api/parser.go
  plugins/parser/example/parser.go
  plugins/parser/example/parser_test.go
  plugins/parser/gork/README.md
  plugins/queue/api/queue.go
  plugins/queue/example/queue.go
  plugins/queue/example/queue_test.go
  plugins/queue/mmap/README.md
Labels: enhancement

#7 delete-plugin-framework-examples
  plugins/client/example/client.go
  plugins/client/example/client_test.go
  plugins/collector/example/collector.go
  plugins/collector/example/collector_test.go
  plugins/fallbacker/example/fallbacker.go
  plugins/fallbacker/example/fallbacker_test.go
  plugins/filter/example/filter.go
  plugins/filter/example/filter_test.go
  plugins/forwarder/example/forwarder.go
  plugins/forwarder/example/forwarder_test.go
  plugins/parser/example/parser.go
  plugins/parser/example/parser_test.go
  plugins/queue/example/queue.go
  plugins/queue/example/queue_test.go
Labels: invalid

#9 ci: require branch to be up to date before merging
  .asf.yaml
  .github/workflows/build-and-test.yaml
Labels: ci settings
