Repository apache/skywalking-satellite, pull requests merged in 2021-09, with the labels that each got.

#64 Polishing documentations
  docs/en/setup/README.md
  docs/en/setup/examples/transmit-log-to-kafka/README.md
  docs/en/setup/examples/transmit-log-to-kafka/satellite_config.yaml
  docs/en/setup/examples/transmit-protocol-from-agent/README.md
  docs/en/setup/examples/transmit-protocol-from-agent/satellite_config.yaml
  docs/en/setup/plugins/fetcher_prometheus-metrics-fetcher.md
  docs/en/setup/plugins/receiver_grpc-nativecds-receiver.md
  docs/en/setup/plugins/receiver_grpc-nativeevent-receiver.md
  docs/en/setup/plugins/receiver_grpc-nativejvm-receiver.md
  docs/en/setup/plugins/receiver_grpc-nativelog-receiver.md
  docs/en/setup/plugins/receiver_grpc-nativemanagement-receiver.md
  docs/en/setup/plugins/receiver_grpc-nativemeter-receiver.md
  docs/en/setup/plugins/receiver_grpc-nativeprofile-receiver.md
  docs/en/setup/plugins/receiver_grpc-nativetracing-receiver.md
  docs/en/setup/plugins/receiver_http-nativelog-receiver.md
  docs/menu.yml
  internal/satellite/tools/generate_plugin_doc.go
  plugins/fetcher/api/fetcher.go
  plugins/fetcher/prometheus/fetcher.go
  plugins/forwarder/grpc/nativeevent/sync_forwarder.go
  plugins/queue/mmap/segment/segment.go
  plugins/receiver/api/receiver.go
  plugins/receiver/grpc/nativecds/receiver.go
  plugins/receiver/grpc/nativeevent/receiver.go
  plugins/receiver/grpc/nativejvm/receiver.go
  plugins/receiver/grpc/nativelog/receiver.go
  plugins/receiver/grpc/nativemanagement/receiver.go
  plugins/receiver/grpc/nativemeter/meter_service.go
  plugins/receiver/grpc/nativemeter/receiver.go
  plugins/receiver/grpc/nativemeter/receiver_test.go
  plugins/receiver/grpc/nativeprofile/receiver.go
  plugins/receiver/grpc/nativetracing/receiver.go
  plugins/receiver/http/nativcelog/receiver.go
Labels: documentation

#66 Prepare release 0.2.0
  CHANGES.md
Labels: chore

#67 Begin version `0.3.0`
  CHANGES.md
  Makefile
  changes/changes-0.2.0.md
  docs/en/guides/contribution/How-to-release.md
  tools/release/create_source_release.sh
Labels: chore

#68 Support load-balance GRPC client with static server list
  docs/en/setup/plugins/client_grpc-client.md
  plugins/client/grpc/client.go
  plugins/client/grpc/client_config.go
  plugins/client/grpc/resolvers/resolvers.go
  plugins/client/grpc/resolvers/static_clients.go
  plugins/client/grpc/static_clients_test.go
Labels: enhancement

#69 Support load-balance GRPC client with Kubenetes selector
  LICENSE
  configs/satellite_config.yaml
  docs/en/setup/README.md
  docs/en/setup/examples/grpc-load-balance-client/README.md
  docs/en/setup/examples/transmit-protocol-from-agent/satellite_config.yaml
  docs/en/setup/plugins/client_grpc-client.md
  docs/menu.yml
  plugins/client/grpc/client.go
  plugins/client/grpc/resolvers/kubernetes_clients.go
  plugins/client/grpc/resolvers/kubernetes_config.go
  plugins/client/grpc/resolvers/kubernetes_kinds.go
  plugins/client/grpc/resolvers/kubernetes_kinds_endpoints.go
  plugins/client/grpc/resolvers/kubernetes_kinds_pod.go
  plugins/client/grpc/resolvers/kubernetes_kinds_service.go
  plugins/client/grpc/resolvers/resolvers.go
  plugins/client/grpc/resolvers/static_clients.go
Labels: enhancement

#70 Add publish docker when each PR merged
  .github/workflows/publish-docker.yaml
Labels: chore

#71 Fix branch name
  .github/workflows/publish-docker.yaml
Labels: chore

#72 Fix wrong Docker registry
  Makefile
Labels: chore

#73 Support generate plugin configuration
  docs/en/setup/plugins/client_grpc-client.md
  docs/en/setup/plugins/client_kafka-client.md
  docs/en/setup/plugins/fallbacker_none-fallbacker.md
  docs/en/setup/plugins/fallbacker_timer-fallbacker.md
  docs/en/setup/plugins/fetcher_prometheus-metrics-fetcher.md
  docs/en/setup/plugins/forwarder_nativecds-grpc-forwarder.md
  docs/en/setup/plugins/forwarder_nativeevent-grpc-forwarder.md
  docs/en/setup/plugins/forwarder_nativejvm-grpc-forwarder.md
  docs/en/setup/plugins/forwarder_nativelog-grpc-forwarder.md
  docs/en/setup/plugins/forwarder_nativelog-kafka-forwarder.md
  docs/en/setup/plugins/forwarder_nativemanagement-grpc-forwarder.md
  docs/en/setup/plugins/forwarder_nativemeter-grpc-forwarder.md
  docs/en/setup/plugins/forwarder_nativeprofile-grpc-forwarder.md
  docs/en/setup/plugins/forwarder_nativetracing-grpc-forwarder.md
  docs/en/setup/plugins/queue_memory-queue.md
  docs/en/setup/plugins/queue_mmap-queue.md
  docs/en/setup/plugins/queue_none-queue.md
  docs/en/setup/plugins/receiver_grpc-nativecds-receiver.md
  docs/en/setup/plugins/receiver_grpc-nativeevent-receiver.md
  docs/en/setup/plugins/receiver_grpc-nativejvm-receiver.md
  docs/en/setup/plugins/receiver_grpc-nativelog-receiver.md
  docs/en/setup/plugins/receiver_grpc-nativemanagement-receiver.md
  docs/en/setup/plugins/receiver_grpc-nativemeter-receiver.md
  docs/en/setup/plugins/receiver_grpc-nativeprofile-receiver.md
  docs/en/setup/plugins/receiver_grpc-nativetracing-receiver.md
  docs/en/setup/plugins/receiver_http-nativelog-receiver.md
  docs/en/setup/plugins/server_grpc-server.md
  docs/en/setup/plugins/server_http-server.md
  docs/en/setup/plugins/server_prometheus-server.md
  go.mod
  go.sum
  internal/satellite/tools/generate_plugin_doc.go
  plugins/client/grpc/client.go
  plugins/client/kafka/client.go
  plugins/queue/mmap/queue.go
  test/e2e/case/native-protocols/expected/service.yml
Labels: documentation, enhancement
