Repository apache/skywalking-satellite, pull requests merged in 2021-01, with the labels that each got.

#12 gRPC server & native log receiver
  dist/LICENSE
  go.mod
  internal/pkg/plugin/definition.go
  internal/pkg/plugin/plugins/democategory/demodir1/demodir2/plugin_test.go
  plugins/queue/mmap/queue.go
  plugins/queue/mmap/queue_test.go
  plugins/receiver/grpc/common.go
  plugins/receiver/grpc/nativelog/log_report_service.go
  plugins/receiver/grpc/nativelog/receiver.go
  plugins/receiver/grpc/nativelog/receiver_test.go
  plugins/receiver/log-grpc/README.md
  plugins/server/grpc/server.go
  plugins/server/prometheus/prometheus.go
  plugins/server/prometheus/prometheus_test.go
Labels: enhancement

#14 add plugin doc generator
  .github/workflows/build-and-test.yaml
  Makefile
  cmd/command.go
  cmd/main.go
  docs/plugin-description.md
  internal/pkg/plugin/registry.go
  internal/satellite/tools/generate_plugin_doc.go
  plugins/fallbacker/timer/timer_fallbacker.go
  plugins/queue/mmap/queue.go
Labels: documentation

#15 chore: optimize the format of the generated document
  docs/plugin-description.md
  internal/satellite/tools/generate_plugin_doc.go
Labels: chore

#17 fix grpc&proto gen version
  go.mod
  go.sum
  protocol/gen-codes/skywalking/network/go.mod
  protocol/gen-codes/skywalking/network/go.sum
  protocol/gen-codes/skywalking/network/language/agent/v3/BrowserPerf_grpc.pb.go
  protocol/gen-codes/skywalking/network/language/agent/v3/CLRMetric_grpc.pb.go
  protocol/gen-codes/skywalking/network/language/agent/v3/JVMMetric_grpc.pb.go
  protocol/gen-codes/skywalking/network/language/agent/v3/Meter_grpc.pb.go
  protocol/gen-codes/skywalking/network/language/agent/v3/Tracing_grpc.pb.go
  protocol/gen-codes/skywalking/network/language/profile/v3/Profile_grpc.pb.go
  protocol/gen-codes/skywalking/network/logging/v3/Logging_grpc.pb.go
  protocol/gen-codes/skywalking/network/management/v3/Management_grpc.pb.go
  protocol/gen-codes/skywalking/network/servicemesh/v3/service-mesh_grpc.pb.go
  tools/protocol_gen.sh
Labels: ci settings

#16 feat: add http logging receiver
  go.sum
  plugins/queue/mmap/queue.go
  plugins/receiver/http/receiver.go
  plugins/receiver/http/receiver_test.go
  plugins/server/http/server.go
Labels: enhancement

#18 Include go.sum|go.mod in CI consistency check
  .github/workflows/build-and-test.yaml
  Makefile
Labels: chore, ci settings

#20 override config by env
  configs/satellite_config.yaml
  internal/satellite/config/loader.go
  internal/satellite/config/override_by_env.go
  internal/satellite/config/override_by_env_test.go
  internal/satellite/config/satellite_config.go
Labels: enhancement
