Repository apache/skywalking-satellite, pull requests merged in 2021-02, with the labels that each got.

#22 add memory queue
  dist/LICENSE
  dist/licenses/LICENSE-goconcurrentqueue.txt
  docs/plugin-description.md
  docs/plugins/queue/mmap/README.md
  go.mod
  go.sum
  internal/satellite/module/gatherer/fetcher_gatherer.go
  internal/satellite/module/gatherer/receiver_gatherer.go
  plugins/queue/api/error.go
  plugins/queue/api/queue.go
  plugins/queue/memory/queue.go
  plugins/queue/memory/queue_test.go
  plugins/queue/mmap/branchmark_test.go
  plugins/queue/mmap/queue.go
  plugins/queue/mmap/queue_opreation.go
  plugins/queue/mmap/queue_test.go
  plugins/queue/queue_repository.go
  plugins/receiver/grpc/nativelog/receiver_test.go
  plugins/receiver/http/nativcelog/receiver_test.go
  plugins/server/grpc/server.go
  plugins/server/http/server.go
Labels: enhancement

#23 polish docs
  .github/workflows/build-and-test.yaml
  Makefile
  README.md
  cmd/command.go
  docs/README.md
  docs/compile/compile.md
  docs/configuration/queue.md
  docs/design/module_structure.md
  docs/en/FAQ/README.md
  docs/en/concepts-and-designs/README.md
  docs/en/concepts-and-designs/module_design.md
  docs/en/concepts-and-designs/overview.md
  docs/en/concepts-and-designs/plugin_mechanism.md
  docs/en/concepts-and-designs/project-goals.md
  docs/en/concepts-and-designs/project_structue.md
  docs/en/guides/README.md
  docs/en/guides/compile/compile.md
  docs/en/guides/contribuation/plugin.md
  docs/en/guides/test/test.md
  docs/en/setup/README.md
  docs/en/setup/configuration/common.md
  docs/en/setup/configuration/override-settings.md
  docs/en/setup/configuration/pipe-plugins.md
  docs/en/setup/configuration/sharing-plugins.md
  docs/en/setup/plugins/client_kafka-client.md
  docs/en/setup/plugins/fallbacker_none-fallbacker.md
  docs/en/setup/plugins/fallbacker_timer-fallbacker.md
  docs/en/setup/plugins/forwarder_nativelog-kafka-forwarder.md
  docs/en/setup/plugins/plugin-list.md
  docs/en/setup/plugins/queue_memory-queue.md
  docs/en/setup/plugins/queue_mmap-queue.md
  docs/en/setup/plugins/receiver_grpc-nativelog-receiver.md
  docs/en/setup/plugins/receiver_http-log-receiver.md
  docs/en/setup/plugins/server_grpc-server.md
  docs/en/setup/plugins/server_http-server.md
  docs/en/setup/plugins/server_prometheus-server.md
  docs/plugin-description.md
  docs/plugins/queue/mmap/README.md
  docs/project_structue.md
  internal/satellite/tools/generate_plugin_doc.go
  plugins/client/kafka/client.go
  plugins/fallbacker/none/none_fallbacker.go
  plugins/fallbacker/timer/timer_fallbacker.go
  plugins/forwarder/kafka/nativelog/sync_forwarder.go
  plugins/queue/memory/queue.go
  plugins/queue/mmap/branchmark_test.go
  plugins/queue/mmap/meta/meta.go
  plugins/queue/mmap/meta/meta_test.go
  plugins/queue/mmap/queue.go
  plugins/queue/mmap/queue_opreation.go
  plugins/queue/mmap/queue_test.go
  plugins/queue/mmap/segment/segment.go
  plugins/queue/mmap/segment/segment_test.go
  plugins/queue/mmap/segment_operation.go
  plugins/server/grpc/server.go
  plugins/server/http/server.go
  plugins/server/prometheus/prometheus.go
Labels: documentation

#25 Polish the doc, setup scripts, and compact the GHA configs
  .gitattributes
  .github/workflows/build-and-test.yaml
  .licenserc.yaml
  Makefile
  README.md
  docs/en/concepts-and-designs/project-goals.md
  docs/en/guides/contribuation/plugin.md
  docs/en/setup/README.md
  docs/en/setup/configuration/common.md
  docs/en/setup/plugins/fallbacker_none-fallbacker.md
  plugins/fallbacker/none/none_fallbacker.go
  plugins/queue/mmap/queue_operation.go
  tools/install_protoc.sh
  tools/protocol_gen.sh
Labels: chore, ci settings

#26 add start up script
  .gitignore
  Makefile
  cmd/main.go
  configs/satellite_config.yaml
  dist/bin/startup.sh
  docker/Dockerfile
  docker/entrypoint.sh
  docs/en/setup/README.md
  docs/en/setup/plugins/server_prometheus-server.md
  internal/satellite/config/loader.go
  internal/satellite/config/loader_test.go
  internal/satellite/config/satellite_config.go
  internal/satellite/module/gatherer/api/config.go
  internal/satellite/module/processor/api/config.go
  internal/satellite/module/sender/api/config.go
  plugins/server/prometheus/prometheus.go
  tools/docker_build.sh
Labels: chore

#28 Optimize Docker image and startup script
  .github/workflows/build-and-test.yaml
  Makefile
  docker/Dockerfile
  docker/docker-compose.yml
  docker/entrypoint.sh
  docs/README.md
  tools/docker_build.sh
Labels: ci settings, enhancement

#29 polish codes for 0.1.0 release
  README.md
  cmd/command.go
  configs/satellite_config.yaml
  docs/en/guides/contribuation/How-to-release.md
  docs/en/setup/plugins/server_grpc-server.md
  internal/satellite/boot/boot.go
  internal/satellite/module/api/module.go
  internal/satellite/module/gatherer/fetcher_gatherer.go
  internal/satellite/module/gatherer/receiver_gatherer.go
  internal/satellite/module/sender/sender.go
  plugins/client/kafka/client.go
  plugins/queue/api/error.go
  plugins/queue/mmap/queue.go
  plugins/server/grpc/server.go
  plugins/server/http/server.go
  plugins/server/prometheus/prometheus.go
Labels: enhancement

#30 add timer fallbacker unit test
  docs/en/setup/plugins/fallbacker_timer-fallbacker.md
  plugins/fallbacker/timer/timer_fallbacker.go
  plugins/fallbacker/timer/timer_fallbacker_test.go
Labels: enhancement

#31 plish timer fallbacker
  docs/en/setup/plugins/fallbacker_timer-fallbacker.md
  plugins/fallbacker/timer/timer_fallbacker.go
  plugins/fallbacker/timer/timer_fallbacker_test.go
Labels: enhancement

#32 add website doc
  changes/changes-0.1.0.md
  docs/en/FAQ/README.md
  docs/en/guides/README.md
  docs/en/guides/compile/How-to-compile.md
  docs/en/guides/contribution/How-to-release.md
  docs/en/guides/contribution/How-to-write-plugin.md
  docs/en/guides/test/How-to-unit-test.md
  docs/menu.yml
Labels: documentation

#33 fix release src cannot compile bug
  Makefile
Labels: bug

#34 add release script
  Makefile
  docs/en/guides/contribution/How-to-release.md
  tools/release/create_bin_release.sh
  tools/release/create_source_release.sh
Labels: ci settings

#35 Fix broken link
  README.md
  docs/en/guides/contribution/How-to-release.md
  docs/en/guides/contribution/How-to-write-plugin.md
Labels: documentation
