Repository apache/skywalking-satellite, pull requests merged in 2021-12, with the labels that each got.

#90 Add documentation for help user deploy the Satellite as Gateway
  configs/satellite_config.yaml
  dist/bin/startup.cmd
  docs/en/FAQ/README.md
  docs/en/FAQ/performance.md
  docs/en/setup/README.md
  docs/en/setup/examples/deploy/kubernetes/README.md
  docs/en/setup/examples/deploy/linux-windows/README.md
  docs/en/setup/examples/feature/enable-disable-channel/README.md
  docs/en/setup/examples/feature/transmit-log-to-kafka/README.md
  docs/en/setup/examples/feature/transmit-log-to-kafka/satellite_config.yaml
  docs/en/setup/examples/forward-agent-data-to-oap-server/README.md
  docs/en/setup/examples/forward-agent-data-to-oap-server/satellite_config.yaml
  docs/en/setup/examples/high-throughput-queue/README.md
  docs/en/setup/performance/als-load-balance/README.md
  docs/menu.yml
  internal/satellite/config/loader_test.go
  plugins/queue/queues_windows.go
Labels: documentation

#91 Begin version `0.5.0`
  CHANGES.md
  changes/changes-0.4.0.md
Labels: chore

#92 Make the gRPC client `client_pem_path` and `client_key_path` as an optional config.
  CHANGES.md
  docs/en/setup/plugins/client_grpc-client.md
  plugins/client/grpc/client_config.go
Labels: enhancement

#93 Fix the gRPC server enable TLS failure
  CHANGES.md
  configs/satellite_config.yaml
  docs/en/setup/examples/deploy/linux-windows/README.md
  docs/en/setup/examples/feature/transmit-log-to-kafka/satellite_config.yaml
  plugins/server/grpc/server.go
Labels: bug

#96 Fix active connection gauge not correct
  internal/satellite/telemetry/metricservice/server.go
  plugins/server/grpc/server_connections.go
Labels: bug

#97 Add the prefix of satellite metrics service
  configs/satellite_config.yaml
  docs/en/setup/examples/feature/telemetry-exporter/README.md
  internal/satellite/telemetry/metricservice/server.go
  internal/satellite/telemetry/telemetry.go
Labels: enhancement

#100 Grammar fix
  README.md
Labels: documentation
