Repository apache/skywalking-satellite, pull requests merged in 2021-08, with the labels that each got.

#59 feat: add Prometheus service discovery in Kubernetes
  configs/satellite_config.yaml
  go.sum
  internal/satellite/config/override_by_env.go
  internal/satellite/module/gatherer/fetcher_gatherer.go
  plugins/fetcher/prometheus/fetcher.go
  plugins/fetcher/prometheus/fetcher_test.go
Labels: enhancement

#58 Support multiple native protocol e2e testing
  .github/workflows/e2e.yaml
  test/e2e/base/base-compose.yml
  test/e2e/base/consumer/Dockerfile
  test/e2e/base/consumer/pom.xml
  test/e2e/base/consumer/src/main/java/org/apache/skywalking/e2e/E2EConfiguration.java
  test/e2e/base/consumer/src/main/java/org/apache/skywalking/e2e/Service1Application.java
  test/e2e/base/consumer/src/main/java/org/apache/skywalking/e2e/User.java
  test/e2e/base/consumer/src/main/java/org/apache/skywalking/e2e/controller/HealthController.java
  test/e2e/base/consumer/src/main/java/org/apache/skywalking/e2e/controller/UserController.java
  test/e2e/base/consumer/src/main/resources/application.yml
  test/e2e/base/provider/Dockerfile
  test/e2e/base/provider/pom.xml
  test/e2e/base/provider/src/main/java/org/apache/skywalking/e2e/KeyValue.java
  test/e2e/base/provider/src/main/java/org/apache/skywalking/e2e/Service0Application.java
  test/e2e/base/provider/src/main/java/org/apache/skywalking/e2e/User.java
  test/e2e/base/provider/src/main/java/org/apache/skywalking/e2e/UserRepo.java
  test/e2e/base/provider/src/main/java/org/apache/skywalking/e2e/controller/HealthController.java
  test/e2e/base/provider/src/main/java/org/apache/skywalking/e2e/controller/UserController.java
  test/e2e/base/provider/src/main/java/test/apache/skywalking/e2e/profile/CreateUser.java
  test/e2e/base/provider/src/main/java/test/apache/skywalking/e2e/profile/ProfileController.java
  test/e2e/base/provider/src/main/resources/application.yml
  test/e2e/base/provider/src/main/resources/log4j.properties
  test/e2e/base/provider/src/main/resources/log4j2.xml
  test/e2e/base/provider/src/main/resources/logback.xml
  test/e2e/base/satellite/Dockerfile
  test/e2e/case/native-protocols/docker-compose.yml
  test/e2e/case/native-protocols/e2e.yaml
  test/e2e/case/native-protocols/expected/etcd-put.yml
  test/e2e/case/native-protocols/expected/event-list.yml
  test/e2e/case/native-protocols/expected/logs-list.yml
  test/e2e/case/native-protocols/expected/metrics-has-value.yml
  test/e2e/case/native-protocols/expected/profile-create.yml
  test/e2e/case/native-protocols/expected/profile-list.yml
  test/e2e/case/native-protocols/expected/profile-segment-analyze.yml
  test/e2e/case/native-protocols/expected/profile-segment-detail.yml
  test/e2e/case/native-protocols/expected/profile-segment-list.yml
  test/e2e/case/native-protocols/expected/service-endpoint.yml
  test/e2e/case/native-protocols/expected/service-instance.yml
  test/e2e/case/native-protocols/expected/service.yml
  test/e2e/case/native-protocols/expected/trace-info-detail.yml
  test/e2e/case/native-protocols/expected/trace-users-detail.yml
  test/e2e/case/native-protocols/expected/traces-list.yml
  test/e2e/case/native-protocols/lal.yaml
Labels: test

#61 Fix failed e2e testing
  .github/workflows/e2e.yaml
  test/e2e/case/native-protocols/e2e.yaml
Labels: chore

#60 docs: add prometheus fetcher documents
  configs/satellite_config.yaml
  docs/en/setup/plugins/fetcher_prometheus-metrics-fetcher.md
  plugins/fetcher/prometheus/fetcher.go
Labels: documentation
