Repository apache/skywalking-satellite, pull requests merged in 2021-06, with the labels that each got.

#43 change go api package
  .github/workflows/build-and-test.yaml
  Makefile
  protocol/satellite-protocol/satellite/Event.proto
Labels: chore

#44 Support gRPC client and transmit native log
  CHANGES.md
  configs/satellite_config.yaml
  docs/en/setup/plugins/client_grpc-client.md
  docs/en/setup/plugins/forwarder_nativelog-grpc-forwarder.md
  docs/en/setup/plugins/plugin-list.md
  internal/satellite/config/loader_test.go
  plugins/client/client_repository.go
  plugins/client/grpc/client.go
  plugins/client/grpc/client_config.go
  plugins/client/grpc/client_sniffer.go
  plugins/forwarder/forwarder_repository.go
  plugins/forwarder/grpc/nativelog/sync_forwarder.go
Labels: documentation, enhancement

#45 feat: add meter forwarder plugin
  CHANGES.md
  docs/en/setup/plugins/forwarder_meter-grpc-forwarder.md
  docs/en/setup/plugins/plugin-list.md
  docs/menu.yml
  plugins/forwarder/forwarder_repository.go
  plugins/forwarder/grpc/meter/sync_forwarder.go
Labels: enhancement

#47 polish scripts and doc when without submodule
  README.md
  docs/en/guides/compile/How-to-compile.md
  docs/en/guides/contribution/How-to-release.md
  tools/release/create_bin_release.sh
  tools/release/create_source_release.sh
Labels: chore

#48 delete gitmodules file
  .gitmodules
Labels: chore

#49 Support generate plugin list index config in menu file
  Makefile
  README.md
  cmd/command.go
  dist/LICENSE
  docs/en/guides/contribution/How-to-write-plugin.md
  docs/menu.yml
  go.mod
  go.sum
  internal/satellite/tools/catalog.go
  internal/satellite/tools/generate_plugin_doc.go
Labels: documentation, enhancement

#50 Remove plugin list page link
  docs/menu.yml
  internal/satellite/tools/generate_plugin_doc.go
Labels: documentation

#42 feat: add prometheus fetcher
  LICENSE
  dist/LICENSE
  docs/en/setup/plugins/fetcher_prometheus_fetcher.md
  docs/en/setup/plugins/plugin-list.md
  go.mod
  go.sum
  internal/satellite/module/gatherer/api/config.go
  internal/satellite/module/gatherer/fetcher_gatherer.go
  plugins/fetcher/api/fetcher.go
  plugins/fetcher/fetcher_repository.go
  plugins/fetcher/prometheus/fetcher.go
  plugins/fetcher/prometheus/fetcher_test.go
  plugins/fetcher/prometheus/metadata.go
  plugins/fetcher/prometheus/metric_builder.go
  plugins/fetcher/prometheus/metric_family.go
  plugins/fetcher/prometheus/queue_appender.go
  plugins/fetcher/prometheus/queue_store.go
  plugins/init.go
Labels: enhancement

#52 Support tracing protocol
  configs/satellite_config.yaml
  docs/en/setup/plugins/fetcher_prometheus-metrics-fetcher.md
  docs/en/setup/plugins/forwarder_nativetracing-grpc-forwarder.md
  docs/en/setup/plugins/plugin-list.md
  docs/en/setup/plugins/receiver_grpc-nativemanagement-receiver.md
  docs/en/setup/plugins/receiver_grpc-nativetracing-receiver.md
  docs/menu.yml
  plugins/forwarder/forwarder_repository.go
  plugins/forwarder/grpc/nativetracing/sync_forwarder.go
  plugins/receiver/grpc/nativetracing/receiver.go
  plugins/receiver/grpc/nativetracing/receiver_test.go
  plugins/receiver/grpc/nativetracing/tracing_report_service.go
  plugins/receiver/receiver_repository.go
Labels: enhancement

#57 add event pipe
  configs/satellite_config.yaml
  docs/en/setup/plugins/fetcher_prometheus_fetcher.md
  docs/en/setup/plugins/forwarder_nativeevent-grpc-forwarder.md
  docs/en/setup/plugins/plugin-list.md
  docs/en/setup/plugins/receiver_grpc-nativeevent-receiver.md
  docs/menu.yml
  internal/satellite/tools/generate_plugin_doc.go
  plugins/forwarder/forwarder_repository.go
  plugins/forwarder/grpc/nativeevent/sync_forwarder.go
  plugins/receiver/grpc/nativeevent/event_service.go
  plugins/receiver/grpc/nativeevent/receiver.go
  plugins/receiver/grpc/nativeevent/receiver_test.go
  plugins/receiver/receiver_repository.go
Labels: enhancement
